
  CREATE TABLE "S_RECORD" 
   (	"RECORD_ID" NUMBER NOT NULL ENABLE, 
	"RESPONSE_ID" NUMBER, 
	"LOCATION_ID" NUMBER, 
	"STAFF_ID" NUMBER, 
	"QUESTION_ID" NUMBER, 
	"SCORE" NUMBER, 
	"ANSWER" VARCHAR2(2040), 
	"LOCATION_LOCATION_ID" NUMBER NOT NULL ENABLE, 
	"STAFF_STAFF_ID" NUMBER NOT NULL ENABLE, 
	"QUESTION_QUESTION_ID" NUMBER NOT NULL ENABLE, 
	"RESPONSE_RESPONSE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RECORD_PK" PRIMARY KEY ("RECORD_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "S_RECORD" ADD CONSTRAINT "RECORD_LOCATION_FK" FOREIGN KEY ("LOCATION_LOCATION_ID")
	  REFERENCES "S_LOCATION" ("LOCATION_ID") ENABLE;
  ALTER TABLE "S_RECORD" ADD CONSTRAINT "RECORD_QUESTION_FK" FOREIGN KEY ("QUESTION_QUESTION_ID")
	  REFERENCES "S_QUESTION" ("QUESTION_ID") ENABLE;
  ALTER TABLE "S_RECORD" ADD CONSTRAINT "RECORD_RESPONSE_FK" FOREIGN KEY ("RESPONSE_RESPONSE_ID")
	  REFERENCES "S_RESPONSE" ("RESPONSE_ID") ENABLE;
  ALTER TABLE "S_RECORD" ADD CONSTRAINT "RECORD_STAFF_FK" FOREIGN KEY ("STAFF_STAFF_ID")
	  REFERENCES "S_STAFF" ("STAFF_ID") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRIG_S_RECORD" 
BEFORE INSERT ON s_record 
FOR EACH ROW
 WHEN (new.record_id IS NULL) BEGIN
  SELECT seq_s_record.NEXTVAL
  INTO   :new.record_id
  FROM   dual;
END;
/
ALTER TRIGGER "TRIG_S_RECORD" ENABLE;