
  CREATE TABLE "S_RESPONSE" 
   (	"RESPONSE_ID" NUMBER NOT NULL ENABLE, 
	"RESPONSE_TIME" DATE DEFAULT TO_DATE ('03-08-2009','mm-dd-RRRR'), 
	 CONSTRAINT "RESPONSE_PK" PRIMARY KEY ("RESPONSE_ID")
  USING INDEX  ENABLE
   ) ;