
  CREATE TABLE "S_STAFF" 
   (	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"STAFF_TITLE" VARCHAR2(255), 
	"STAFF_NAME" VARCHAR2(255), 
	"SORT_ORDER" VARCHAR2(255), 
	 CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFF_ID")
  USING INDEX  ENABLE
   ) ;